# app.py
from rules import check_request
from flask import Flask, request, Response
import requests
import json

app = Flask(__name__)

# Catch-all route that captures any path, including the root "/".
# Methods allowed: GET, POST, PUT, DELETE (as required).
@app.route('/', defaults={'subpath': ''}, methods=['GET', 'POST', 'PUT', 'DELETE'])
@app.route('/<path:subpath>', methods=['GET', 'POST', 'PUT', 'DELETE'])
def proxy(subpath):
    """
    Reverse proxy endpoint.
    Captures every request, extracts metadata, forwards it to the target app,
    and returns the target's response unchanged.
    """

    # ---------- 1. Extract incoming request data ----------
    method = request.method
    full_url = request.url                     # e.g. http://localhost:5000/search?q=test
    path = request.path                        # e.g. /search
    query_params = request.args.to_dict(flat=False)  # preserves multiple values
    headers = dict(request.headers)            # all incoming HTTP headers
    cookies = request.cookies.to_dict()        # incoming cookies
    client_ip = request.remote_addr            # client IP address
    raw_body = request.get_data()              # raw request body (bytes)

    # Parse JSON if the request Content-Type is application/json
    json_data = None
    if request.is_json:
        json_data = request.get_json(silent=True)

    # Parse form data (application/x-www-form-urlencoded)
    form_data = request.form.to_dict(flat=False)

    # Store everything in a dict
    request_data = {
        "method": method,
        "full_url": full_url,
        "path": path,
        "query_params": query_params,
        "headers": headers,
        "cookies": cookies,
        "client_ip": client_ip,
        "raw_body": raw_body.decode('utf-8', errors='replace'),
        "form_data": form_data,
        "json_data": json_data
    }

    # ---------- 2. Log the captured request data (for WAF inspection later) ----------
    print("========== Incoming Request ==========")
    print(json.dumps(request_data, indent=2, default=str))
    print("======================================\n")

    # ---------- 3. Forward the request to the target app ----------
    target_base = "http://localhost:5001"
    target_url = target_base + path

    # Copy incoming headers, but remove Host and Cookie.
    # Host: we let requests set the correct target Host header.
    # Cookie: we will pass cookies separately via the cookies parameter.
    forward_headers = dict(request.headers)
    forward_headers.pop('Host', None)
    forward_headers.pop('Cookie', None)

    try:
        # Forward the request with the same method, path, query params, body, and cookies.
        # allow_redirects=False makes the proxy transparent (does not follow redirects itself).
        target_response = requests.request(
            method=method,
            url=target_url,
            params=query_params,          # query string as dict with list values
            headers=forward_headers,
            cookies=cookies,
            data=raw_body,                # raw body bytes
            allow_redirects=False
        )
    except requests.exceptions.RequestException as e:
        # If the target app is unreachable, return a 502 Bad Gateway response.
        return Response(f"Proxy error: {e}", status=502)

    # ---------- 4. Return the target's response unchanged ----------
    response_headers = dict(target_response.headers)

    # Remove hop-by-hop headers that must not be forwarded by a proxy.
    # These headers are connection-specific and will be regenerated by Flask.
    for header in ['content-encoding', 'content-length', 'transfer-encoding', 'connection']:
        response_headers.pop(header, None)

    # Return the target's body, status code, and headers.
    return Response(
        target_response.content,
        status=target_response.status_code,
        headers=response_headers
    )


if __name__ == '__main__':
    # Run the WAF reverse proxy on port 5000.
    app.run(host='0.0.0.0', port=5000)